baseURL = "https://ixai.mx/"
languageCode = "en-us"
title = "Ixai"
theme = "paper"

[params]
author = "Ixai Lanzagorta"
twitter = "ixai"
instagram = "ixailanza"
github = "ixai"
linkedin = "/in/ixailanzagorta/"

[[menu.main]]
url = "/about/"
name = "About"
weight = 1
